version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: go-vulnerable-db
    # Evitamos mapear 5432:5432 para evitar conflictos en el host de Jenkins
    # La API y ZAP se comunicarán internamente por la red.
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user
      # Sugerencia: En producción usa Jenkins Credentials y envíalo como variable
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mydatabase
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data:rw
    networks:
      - jenkins-net
    # Seguridad: Limitar recursos (Corrige alertas MEDIUM de KICS)
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-vulnerable-api
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - jenkins-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

# --- LA SOLUCIÓN DEFINITIVA ---
networks:
  jenkins-net:
    external: true
    name: jenkins-net